config/routes.rb
Rails.application.routes.draw do
  default_url_options :host => "localhost:3000"
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root :to => "web/boards#show"
  
  scope module: :web do
    resource :board, only: :show
    resource :session, only: [:new, :create, :destroy]
    resources :developers, only: [:new, :create]
    resource :password, only: [:new, :create, :edit, :update]
  end

  namespace :admin do
    resources :users
  end

  namespace :api do
    namespace :v1 do
      resources :tasks, only: [:index, :show, :create, :update, :destroy] do
        member do
          put :attach_image
          delete :remove_image
        end
      end
      resources :users, only: [:index, :show]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :my_tasks, class_name: 'Task', foreign_key: :author_id
  has_many :assigned_tasks, class_name: 'Task', foreign_key: :assignee_id

  validates :first_name, presence: true, length: { minimum: 2 }
  validates :last_name, presence: true, length: { minimum: 2 }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true

  HOURS_VALID = 24

  def self.new_token
    token = SecureRandom.urlsafe_base64

    while User.find_by(password_reset_token: token)
      token = SecureRandom.urlsafe_base64
    end

    token
  end

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def create_password_reset_token
    self.password_reset_token = User.new_token
    update(password_reset_token: User.digest(password_reset_token), password_reset_token_sent_at: Time.zone.now)
  end

  def remove_password_reset_token
    update(password_reset_token: nil, password_reset_token_sent_at: nil)
  end

  def password_reset_token_expired?
    password_reset_token_sent_at < HOURS_VALID.hours.ago
  end

  def self.find_and_validate_password_reset_token(token)
    user = User.find_by(password_reset_token: token)
    if user && !user.password_reset_token_expired?
      user
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @q = User.ransack(params[:q])
    @users = @q.result.order(:type).order(:id).page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to(admin_users_url)
    else
      render(:new_admin_user_url)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to(admin_users_url)
    else
      render(:edit)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to(admin_users_path)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :type)
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController
  def show
    user = User.find(params[:id])

    respond_with(user, serializer: UserSerializer)
  end

  def index
    users = User.ransack(ransack_params).result.page(page).per(per_page)

    respond_with(users, each_serializer: UserSerializer, meta: build_meta(users), root: 'items')
  end
end

app/views/admin/users/_form.html.slim
= simple_form_for @user, as: :user, url: url do |f|
  h4= h4
  p
    = f.input :first_name
    = f.input :last_name
    = f.input :email
    = f.input :password
    = f.input :type, as: :select, collection: ['Admin', 'Manager', 'Developer']
  p
    = f.button :submit, "Confirm", class: 'mdl-button--colored'
    = f.button :submit, "Back", formaction: admin_users_url, formmethod: "get"

app/views/admin/users/edit.html.slim
= render "form", h4: "Edit user", url: admin_user_path(@user)

app/views/admin/users/index.html.slim
h3 Users list
.mdl-grid
  .mdl-cell.mdl-cell--2-col
    = link_to "Add new user", new_admin_user_path, class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored"
  .mdl-cell.mdl-cell--8-col
  .mdl-cell.mdl-cell--2-col
    = search_form_for(@q, url:admin_users_url, method: :get) do |f|
      .mdl-textfield.mdl-js-textfield
        = f.search_field :email_cont, class: 'mdl-textfield__input'
        = f.label :email_cont, class: 'mdl-textfield__label' do
          i.material-icons search
.mdl-grid
  table.mdl-cell--12-col.mdl-data-table.mdl-js-data-table.mdl-shadow--2dp
    thead
      tr
        th= sort_link(@q, :id, "#")
        th= sort_link(@q, :first_name, "First Name")
        th= sort_link(@q, :last_name, "Last Name")
        th= sort_link(@q, :email, "Email")
        th= sort_link(@q, :type, "Type")
        th scope="col"  Actions
    tbody
      - @users.each do |user|
        tr
          td= user.id
          td= user.first_name
          td= user.last_name
          td= user.email
          td= user.type
          td
            => link_to "Edit", edit_admin_user_path(user)
            -if current_user.id != user.id
              =< link_to "Delete", admin_user_path(user), method: "delete"

.mdl-grid
  .mdl-cell.mdl-cell--10-col
    = paginate @users
  .mdl-cell.mdl-cell--2-col
    = page_entries_info @users

app/views/admin/users/new.html.slim
= render "form", h4: "Create new user", url: admin_users_path

app/views/admin/users/show.html.slim
h1 User profile
p
  span First Name:&nbsp;
  strong= @user.first_name
p
  span Last Name:&nbsp;
  strong= @user.last_name
p
  span Email:&nbsp;
  strong= @user.email

= link_to "Back to index", admin_users_path